# -*- coding: utf-8 -*-
"""GEOLOCATION1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rpfCf_HnsqnWhcrE_jf14K8Z74s-Sj8g
"""

with gr.Blocks(
    theme=gr.themes.Base(),
    css="""
    @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Poppins:wght@300;500&display=swap');

    body {
        background: linear-gradient(135deg, #1a0033, #4b0082, #6a0dad);
        font-family: 'Poppins', sans-serif;
    }

    .gradio-container {
        background: rgba(255, 255, 255, 0.08);
        backdrop-filter: blur(15px);
        border-radius: 20px;
        padding: 30px;
        box-shadow: 0 0 40px rgba(192, 132, 252, 0.6);
    }

    h1 {
        font-family: 'Playfair Display', serif;
        font-size: 42px;
        text-align: center;
        color: #e0b3ff;
        letter-spacing: 2px;
    }

    .subtitle {
        text-align: center;
        color: white;
        font-size: 18px;
        margin-bottom: 25px;
    }

    .gr-button {
        background: linear-gradient(90deg, #9333ea, #c084fc);
        color: white;
        font-weight: bold;
        border-radius: 12px;
    }

    .gr-textbox {
        background-color: rgba(255,255,255,0.1);
        color: white;
    }
    """
) as demo:

    gr.Markdown(
        """
        <h1>Image Geolocation Risk Analyzer</h1>
        <div class="subtitle">
        Detect hidden GPS metadata, device model & timestamp from digital images.
        </div>
        """
    )

    image_input = gr.File(label="📂 Upload Image")

    analyze_button = gr.Button("🚀 Analyze Image")

    output_text = gr.Textbox(label="🔍 Analysis Report", lines=15)

    analyze_button.click(analyze_image, inputs=image_input, outputs=output_text)

demo.launch()

